function f_state = system_ode(t,in2)
%SYSTEM_ODE
%    F_STATE = SYSTEM_ODE(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-May-2019 09:39:01

x5 = in2(1,:);
x6 = in2(2,:);
t2 = x6+4.0./5.0;
t3 = 1.0./t2;
f_state = [t3.*x5.*x6.*(6.0./5.0);t3.*x5.*x6.*(-2.0./5.0)];
